### ISSUE TITLE
error validating data: API version "federation/v1beta1"

### ISSUE THREAD

**Issue by yahavb** [kelseyhightower/kubernetes-cluster-federation#10]
After finishing the control plane deployment (passing the Deploy the Federated Controller Manager section). I was trying to deploy a cluster using "Adding Clusters" section I executed:
kubectl --context=federation-cluster create -f clusters/gce-asia-east1.yaml

error validating "clusters/cdn-edg-us-central1-b.yaml": error validating data: API version "federation/v1beta1" isn't supported, only supports API versions ["batch/v1" "autoscaling/v1" "authorization.k8s.io/v1beta1" "v1" "metrics/v1alpha1" "extensions/v1beta1" "componentconfig/v1alpha1"]; if you choose to ignore these errors, turn validation off with --validate=false

When I choose to ignore validation I get:
unable to decode "clusters/gce-asia-east1.yaml": no kind "Cluster" is registered for version "federation/v1beta1"

Also, I followed the tutorial stop by step and I am not sure what can did I miss. I must miss something though...

HELP please

**Comment by kelseyhightower** [comment]
@yahavb This should all be working on master. There are lots of updates for the new 1.4 stuff. Check it out.
