### ISSUE TITLE
kubectl create -f pvc/federation-apiserver-etcd.yaml

### ISSUE THREAD

**Issue by jamesbuckett** [kelseyhightower/kubernetes-cluster-federation#12]
When executing `kubectl create -f pvc/federation-apiserver-etcd.yaml`

Error `federation-apiserver-etcd.yaml does not exist`

Check `/pvc` and find only `etcd.yaml`

Assume correct file to use is `etcd.yaml` ?

**Comment by kelseyhightower** [comment]
This is fixed on master. Thanks for reporting it!
