### ISSUE TITLE
kubectl create -f deployments/federation-apiserver.yaml

### ISSUE THREAD

**Issue by jamesbuckett** [kelseyhightower/kubernetes-cluster-federation#13]
While running `kubectl create -f deployments/federation-apiserver.yaml`

Error is returned 
`root@ibm-ubuntu-1gb-sfo1-01:~/kubernetes-cluster-federation/deployments# kubectl create -f federation-apiserver.yaml
The Deployment "federation-apiserver" is invalid.
spec.template.spec.volumes[1].name: Required value
`

**Comment by kelseyhightower** [comment]
This should be fixed now.
