### ISSUE TITLE
"Create a Google DNS Managed Zone" section fails

### ISSUE THREAD

**Issue by wattsteve** [kelseyhightower/kubernetes-cluster-federation#19]
Hi Kelsey, I made my way over here from the Storage SIG because I think this is the only working Kube Federation guide out there (including our official docs!). Firstly, thanks for this awesome guide. Second point, I'm not very familiar with GCE, so this may be a n00b issue, but I'm following the guide verbatim and it looks like the command is failing here because its expecting a real domain name? Any suggestions? 

wattstevej@fedimages-143511:~/kubernetes-cluster-federation$ gcloud dns managed-zones create federation   --description "Kubernetes federation testing"   --dns-name federation.com
ERROR: (gcloud.dns.managed-zones.create) 
Please verify ownership of the 'federation.com.' domain (or a parent) at http://www.google.com/webmasters/verification/ and try again (code: 400)

**Comment by wattsteve** [comment]
For other folks that wound up here with the same issue. I've confirmed with the Kube Federation-SIG that as of Kube 1.4, Kube-Federation requires a real domain name. I believe this is because the only current Federation DNS Services supported are AWS Route 53 and Google Cloud DNS, and they require a real domain name.

**Comment by ohohoreilly** [comment]
Thanks for sharing the tip @wattsteve I'm sure that'll be quite helpful to folks. I wonder if we could make a wildcard DNS entry for making testing this for others easier. I'd be interested to hear @kelseyhightower thoughts on that.

**Comment by kelseyhightower** [comment]
I've updated the managed DNS section to use a `.local` name to prevent errors because you don't own the domain.
