### ISSUE TITLE
Does kubernetes federation work outside GKE/GCE ?

### ISSUE THREAD

**Issue by tiagoalves83** [kelseyhightower/kubernetes-cluster-federation#23]
@kelseyhightower Does kubernetes federation work outside GKE/GCE ? https://github.com/kubernetes/kubernetes/blob/master/federation/deploy/deploy.sh#L53

I have tried building a local virtualized environment without success. It seems that Federation only works with GCE/GKE providers. Is there a workaround for the deploy.sh script using other providers?

**Comment by madhusudancs** [comment]
@tiagoalves83 that line you are pointing to is a bug.

Federation works on any Kubernetes cluster. There are two caveats though:
1. You need a DNS provider for federated services to work. There are implementations for only two providers right now: AWS Route53 and Google Cloud DNS. CoreDNS support is coming soon. But this doesn't mean you need to run your clusters in either of these cloud providers. You can run your cluster anywhere, but you will need access to one of these providers for federated services to work. But you can choose to not use federated services if you don't want it.
2. Federated Ingress is only tested on GCP at the moment.

**Comment by lsztachanski** [comment]
@madhusudancs 
2. creating federated services invokes ingress. It  has been confirmed not to work (out-of-the-box) with hybrid/bare-metal setup https://github.com/kubernetes/kubernetes/issues/33943
We'll try to implement ingress controller inside the bare-metal cluster and see if it allows proper service scheduling across federated clusters (cc: @MichalMankowski)

**Comment by madhusudancs** [comment]
@lsztachanski  

>  creating federated services invokes ingress

Creating a federated service doesn't invoke Ingress. 

However, when you start the federation controller manager, it starts the Federated Ingress controller too. See the comment here - https://github.com/kubernetes/kubernetes/issues/33943#issuecomment-252953294. It is just that the error message is spurious in that case and should be suppressed. It doesn't affect the functioning of other federated resources including federated services.

> We'll try to implement ingress controller inside the bare-metal cluster and see if it allows proper service scheduling across federated clusters (cc: @MichalMankowski)

Sure, thanks! Also for clarity, Service is a resource that is independent of Ingress. Ingresses need Services as targets, but not the other way round. Federated Services function irrespective of Ingresses.

**Comment by lsztachanski** [comment]
@madhusudancs @tiagoalves83 

We've (cc @MichalMankowski @lluczaj) deployed federation in every possible scenario. ReplicaSets, Namespaces, Secrets work on federated cluster, regardless of setup specification.  On-premise-only, hybrid or GKE-only.
**Services work only on GKE.**

All informations regarding _Federated Services_ are provided in https://github.com/kubernetes/kubernetes/issues/33943#issuecomment-252953294

**Comment by tiagoalves83** [comment]
@lsztachanski Can you share your on-premise federation setup ?
