### ISSUE TITLE
Failure when starting controller manager

### ISSUE THREAD

**Issue by cooktheryan** [kelseyhightower/kubernetes-cluster-federation#24]
I1109 19:30:14.509494       1 servicecontroller.go:267] DNS zone "federation.com." not found.  Creating DNS zone "federation.com.".
E1109 19:30:14.640004       1 controllermanager.go:174] Failed to start service controller: googleapi: Error 400: Please verify ownership of the 'federation.com.' domain (or a parent) at http://www.google.com/webmasters/verification/ and try again, verifyManagedZoneDnsNameOwnership

**Comment by kelseyhightower** [comment]
I've improved the instructions on deploying the controller manager and setting up DNS. We are now using the 1.5.5 release so I expect many bugs have been fixed.
