### ISSUE TITLE
Use kubefed

### ISSUE THREAD

**Issue by ahmetb** [kelseyhightower/kubernetes-cluster-federation#32]
It looks like kubefed (beta as of 1.6) eliminates and simplifies a lot of the steps described in this tutorial. Should this repo move to using kubefed instead or is the intent to keep is as is to explain the inner workings of how Federation works?

**Comment by kelseyhightower** [comment]
kubefed hides the details people need to know. So the goal is to document all the things that kubefed does under the covers.
