### ISSUE TITLE
Add clarity to the statement "add a token" to the Federation API Server Secret

### ISSUE THREAD

**Issue by DazWilkin** [kelseyhightower/kubernetes-cluster-federation#5]
https://github.com/kelseyhightower/kubernetes-cluster-federation#federation-api-server-secret

I believe (!?) the token may be any random string but it would be useful to clarify this in the instructions.

**Comment by kelseyhightower** [comment]
@DazWilkin Good call, I'll add this.

**Comment by kelseyhightower** [comment]
I've updated the guide to just generate a random token.
