### ISSUE TITLE
Suggestion: refactor project and zone from commands

### ISSUE THREAD

**Issue by DazWilkin** [kelseyhightower/kubernetes-cluster-federation#7]
Then offer the guidance to iterate over all the zones once

```
for ZONE in asia-east1 europe-west1 us-central1 us-east1;
do
  [YOUR COMMAND HERE]
done
```

And list the per zone commands once:

```
kubectl --context=gke_${PROJECT}_${ZONE}-b_gce-${ZONE} \
get svc nginx;
```

**Comment by kelseyhightower** [comment]
I'm following this pattern in a lot more places. Now the cluster names match the zone names and I've reduced a great number of steps as a result.
